;;; git-blamed-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from git-blamed.el

(autoload 'git-blamed-mode "git-blamed" "\
Toggle minor mode for displaying Git blame

With prefix ARG, turn the mode on if ARG is positive.

(fn &optional ARG)" t)
(autoload 'git-reblame "git-blamed" "\
Recalculate all blame information in the current buffer" t)
(register-definition-prefixes "git-blamed" '("git-" "in-blame-filter" "remove-git-blamed-text-properties"))

;;; End of scraped data

(provide 'git-blamed-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; git-blamed-autoloads.el ends here
