;;; hippie-expand-slime-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hippie-expand-slime.el

(autoload 'try-expand-slime "hippie-expand-slime" "\
Simple slime completion function for `hippie-expand'.

(fn OLD)")
(autoload 'try-expand-slime-fuzzy "hippie-expand-slime" "\
Fuzzy slime completion function for `hippie-expand'.

(fn OLD)")
(autoload 'set-up-slime-hippie-expand "hippie-expand-slime" "\
Add an optionally-fuzzy slime completion function to the front of
`hippie-expand-try-functions-list' for the current buffer.

(fn &optional FUZZY)" t)
(register-definition-prefixes "hippie-expand-slime" '("hippie-expand-slime-fuzzy-completions" "try-expand-slime-with-fn"))

;;; End of scraped data

(provide 'hippie-expand-slime-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hippie-expand-slime-autoloads.el ends here
