;;; dsvn-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dsvn.el

(register-definition-prefixes "dsvn" '("create-svn-buffer" "set-svn-process-status" "svn-" "switch-to-svn-buffer"))

;;; End of scraped data

(provide 'dsvn-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dsvn-autoloads.el ends here
