;;; ghci-completion-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ghci-completion.el

(autoload 'turn-on-ghci-completion "ghci-completion" "\
Turn on GHCi completion mode.")
(autoload 'ghci-completion-mode "ghci-completion" "\
GHCi completion mode.
Provides basic TAB-completion of GHCi commands.

(fn &optional ARG)" t)
(register-definition-prefixes "ghci-completion" '("ghci-completion-" "pcomplete/:" "turn-off-ghci-completion"))

;;; End of scraped data

(provide 'ghci-completion-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ghci-completion-autoloads.el ends here
