;;; idomenu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from idomenu.el

(autoload 'idomenu "idomenu" "\
Switch to a buffer-local tag from Imenu via Ido." t)
(register-definition-prefixes "idomenu" '("idomenu--"))

;;; End of scraped data

(provide 'idomenu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; idomenu-autoloads.el ends here
