;;; ac-haskell-process-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ac-haskell-process.el

(defconst ac-source-haskell-process '((available . ac-haskell-process-available-p) (candidates . ac-haskell-process-candidates) (document . ac-haskell-process-doc) (symbol . "h")) "\
Haskell auto-complete source which uses the current haskell process.")
(autoload 'ac-haskell-process-setup "ac-haskell-process" "\
Add the haskell process completion source to the front of `ac-sources'.
This affects only the current buffer." t)
(autoload 'ac-haskell-process-popup-doc "ac-haskell-process" "\
Show documentation for the symbol at point in a popup." t)
(register-definition-prefixes "ac-haskell-process" '("ac-haskell-process-"))

;;; End of scraped data

(provide 'ac-haskell-process-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ac-haskell-process-autoloads.el ends here
