;;; elein-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elein.el

(autoload 'elein-swank "elein" "\
Launch lein swank and connect slime to it.  Interactively, a
PREFIX means launch a standalone swank session without a
project.

(fn &optional PREFIX)" t)
(autoload 'elein-kill-swank "elein" "\
Kill swank process started by lein swank." t)
(autoload 'elein-reswank "elein" "\
Kill current lisp, restart lein swank and connect slime to it." t)
(autoload 'elein-run-cmd "elein" "\
Run 'lein ARGS' using `compile' in the project root directory.

(fn ARGS)" t)
(autoload 'elein-run-task "elein" "\
Run 'lein TASK' using `compile' in the project root directory.

(fn TASK)" t)
(register-definition-prefixes "elein" '("elein-"))

;;; End of scraped data

(provide 'elein-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elein-autoloads.el ends here
