;;; lively-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lively.el

(autoload 'lively "lively" "\
Make the expression before point lively." t)
(autoload 'lively-region "lively" "\
Make the region from START to END lively.

(fn START END)" t)
(register-definition-prefixes "lively" '("lively-"))

;;; End of scraped data

(provide 'lively-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lively-autoloads.el ends here
